#!/bin/sh

rm -f *.ior

echo "Starting collector server"

lua collector.lua &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i)) ; do
	if test -r c1.ior && test -r c2.ior && test -r c3.ior && test -r adaptor.ior
		then break
		else sleep 1
	fi
done

echo "Starting client"

lua client.lua &
client_pid=$!

trap "kill $server_pid $client_pid > /dev/null 2> /dev/null" 0

echo "Execute for 10 secs. (note e-mail duplications)"

sleep 10

echo
echo "*********************"
echo "*** Adapt server! ***"
echo "*********************"
echo

lua adaptation.lua

echo "Execute for 10 secs. without duplications"

sleep 10

echo "Demo finished."

rm -f *.ior
