#!/bin/sh

LUA=lua

echo "Starting server"
$LUA server.lua &
pids="$pids $!"
trap "kill $pids > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i));do if test -r ref.ior;then break;else sleep 1;fi;done

echo "Starting client"
$LUA client.lua &
pids="$pids $!"
trap "kill $pids > /dev/null 2> /dev/null" 0

echo "Execute for 30 secs. for a deadlock situation"
sleep 30

rm -f ref.ior
