#!/bin/sh

echo "Starting server"

rm -f hello.ref
lua server.lua &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i)); do
	if test -r hello.ref
		then break
		else sleep 1
	fi
done

echo "Starting client"

lua client.lua

echo "Demo finished."

rm -f hello.ref
