# makefile for O2 Pre-Compiled Test Application

OIL= ..\..

!include $(OIL)\config.win32

OBJS=	run.obj

SRCS=	run.c

PRELOAD=	/DPRELOAD
!if "$(PRELOAD)" == ""
OILLIB=	oilbit.lib
!else
OILLIB=	oilall.lib
!endif

CFLAGS= $(CFLAGS) /I$(OIL)\src $(PRELOAD)
LDFLAGS= $(LDFLAGS) /LIBPATH:$(OIL)\src
LIBS= $(LIBS) lua.lib wsock32.lib luasocket.lib $(OILLIB)

T= run.exe

all: $T

$T:	$(OBJS)
	$(LINK) $(LDFLAGS) $(LIBS) /out:$@ $(OBJS)
	
clean:
	-del $T $(OBJS)
