#!/bin/sh

VERSION=0.5
RELEASE=

PACKAGE=oil-$VERSION-$RELEASE

for plat in vc6 vc7 vc8; do
	mkdir $PACKAGE-$plat
	for lib in loop luaidl socket oil; do
		cp lib/$plat/lualib$lib.lib $PACKAGE-$plat
		cp obj/lualib$lib/$plat/lualib$lib.h $PACKAGE-$plat
	done
	zip -r $PACKAGE-$plat.zip $PACKAGE-$plat
	rm -fR $PACKAGE-$plat
done

for plat in dll dll7 dll8; do
	mkdir $PACKAGE-$plat
	for lib in loop luaidl socket oil; do
		cp lib/$plat/lualib$lib.{exp,lib,dll} $PACKAGE-$plat
		cp obj/lualib$lib/$plat/lualib$lib.h $PACKAGE-$plat
	done
	zip -r $PACKAGE-$plat.zip $PACKAGE-$plat
	rm -fR $PACKAGE-$plat
done

PACKAGE=oilall-$VERSION-$RELEASE

for plat in vc6 vc7 vc8; do
	mkdir $PACKAGE-$plat
	cp lib/$plat/oilall.lib $PACKAGE-$plat
	cp src/oilall.h $PACKAGE-$plat
	zip -r $PACKAGE-$plat.zip $PACKAGE-$plat
	rm -fR $PACKAGE-$plat
done

for plat in dll dll7 dll8; do
	mkdir $PACKAGE-$plat
	cp lib/$plat/oilall.{exp,lib,dll} $PACKAGE-$plat
	cp src/oilall.h $PACKAGE-$plat
	zip -r $PACKAGE-$plat.zip $PACKAGE-$plat
	rm -fR $PACKAGE-$plat
done

PACKAGE=oil-$VERSION-$RELEASE-win32
mkdir $PACKAGE
cp $LUA51/bin/Win32/* $PACKAGE
mkdir $PACKAGE/oil   ; cp lib/dll8/oilbit.dll    $PACKAGE/oil/bit.dll
mkdir $PACKAGE/socket; cp lib/dll8/luasocket.dll $PACKAGE/socket/core.dll
cp -R lua $PACKAGE
cp -R demo $PACKAGE
find $PACKAGE/demo -type f -iname execute | xargs rm -f
zip -r $PACKAGE.zip $PACKAGE
rm -fR $PACKAGE
