#!/bin/sh

echo "Starting philosopher's server"

rm -f *.ior

lua philo.lua &
philo_pid=$!

trap "kill $philo_pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i));do if test -r philo.ior;then break;else sleep 1;fi;done

echo "Starting fork server"

lua fork.lua &
fork_pid=$!

trap "kill $philo_pid $fork_pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i));do if test -r fork.ior;then break;else sleep 1;fi;done

echo "Starting observer server"

lua observer.lua &
observer_pid=$!

trap "kill $philo_pid $fork_pid $observer_pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i));do if test -r observer.ior;then break;else sleep 1;fi;done

echo "Configuring and starting application"

lua config.lua

echo "Execute for 30 secs. for a deadlock situation"

sleep 30

echo "Adapt application to prevent deadlocks"

lua adapt.lua

echo "Execute for more 30 secs."

sleep 30

echo "Demo finished."

rm -f *.ior
