# makefile for O2 Pre-Compiled Test Application

OIL= ..\..

!include $(OIL)\config.win32

OBJS=	oilaccess.obj \
      hello.obj \
      main.obj

INCS= /I$(LUA5_INC) /I$(INC_DIR)
LIBS= /libpath:$(LIB_DIR) lua.lib lualib.lib compat51r3.lib lsocket.lib bitlib.lib

CPPFLAGS= /GX $(INCS)

T= servant.exe

all: $T

$T:	$(OBJS)
	$(LINK) $(LDFLAGS) $(LIBS) /out:$@ $(OBJS)
	
clean:
	-del $T $(OBJS)
