#!/bin/sh

#SVNBASE=https://subversion.tecgraf.puc-rio.br/engsoftware/
SVNBASE=/Users/maia/Work/proj/

LUAIDL_VERSION=0.9
LUAIDL_RELEASE=beta
LUAIDL_PACKAGE=luaidl-$LUAIDL_VERSION-$LUAIDL_RELEASE

mkdir $LUAIDL_PACKAGE
cd $LUAIDL_PACKAGE
svn export --force $SVNBASE/oil/trunk/lua/luaidl
svn export --force $SVNBASE/oil/trunk/lua/luaidl.lua
cd ..
tar -czvf $LUAIDL_PACKAGE.tar.gz $LUAIDL_PACKAGE/
zip -r $LUAIDL_PACKAGE.zip $LUAIDL_PACKAGE/
rm -fR $LUAIDL_PACKAGE/

OIL_VERSION=0.5
OIL_RELEASE=beta
OIL_PACKAGE=oil-$OIL_VERSION-$OIL_RELEASE

curl -C - -O http://luaforge.net/frs/download.php/2664/luasocket-2.0.2.tar.gz
tar -xzvf luasocket-2.0.2.tar.gz

if [ ! -d $OIL_PACKAGE ]; then mkdir $OIL_PACKAGE; fi
mv luasocket-2.0.2/src $OIL_PACKAGE/src
rm -fR luasocket-2.0.2 luasocket-2.0.2.tar.gz

cd $OIL_PACKAGE
mkdir -p lua/socket
rm -f src/ltn12.lua
rm -f src/mime.*
mv src/socket.lua lua/
mv src/*.lua lua/socket/
rm -f src/makefile
cd ..

svn export --force $SVNBASE/oil/trunk $OIL_PACKAGE
svn export --force $SVNBASE/loop/branches/LOOP_2_3/lua $OIL_PACKAGE/lua
svn export --force $SVNBASE/loop/branches/LOOP_2_3/doc/build.lua $OIL_PACKAGE/doc/build.lua

cd $OIL_PACKAGE
# pack files to build Windows binaries
cd etc/tecmake
tar -czvf ../../../oil-tecmake.tar.gz *
cd ../../
mv etc/tecmake/README.TXT ../
rm -fR etc
# build docs and remove unecessary files
cd doc; lua build.lua sitemap.lua .; cd ..
rm -f doc/build.lua
rm -f doc/sitemap.lua
# remove file with history of the project
rm -f HISTORY
# remove MS-NMake support for Windows
rm -f config.win32
find . -type f -name Makefile.win32 | xargs rm -f
# remove demos not updated to lastest version
rm -fR demo/hello_ssl
rm -fR demo/minimal
rm -fR demo/proxy
# remove test suite
rm -fR test
# remote LOOP classes that are still draft
rm -fR lua/loop/test
cd ..

tar -czvf $OIL_PACKAGE.tar.gz $OIL_PACKAGE/
zip -r $OIL_PACKAGE.zip $OIL_PACKAGE/
rm -fR $OIL_PACKAGE/
