#ifndef AS_IDL
#define AS_IDL

#include "scs.idl"
#include "life_cycle.idl"
#include "registry_service.idl"

module OpenBus {

module AS {

typedef long Identifier;

struct Credential {
    long id;
    string entityName;
};

interface CredentialResource : LifeCycle::Resource {
    Identifier getIdentifier();
    Credential getCredential();
};

interface CredentialManagerObserver {
    void credentialWasDeleted(in Credential credential);
};

interface CredentialManagerObservable {
    void addObserver(in CredentialManagerObserver observer);
    void removeObserver(in CredentialManagerObserver observer);
};

interface AccessControlService : CredentialManagerObservable, LifeCycle::Stethoscope {
    Identifier loginByCredential (in Credential credential, in LifeCycle::Heart heart);
    Credential loginByPassword (in string name, in string password); 
    void logout (in Identifier identifier);
    boolean validate (in Credential credential);
    RS::RegistryService getRegistryService (in Credential credential);
};

};

};

#endif
