module eventflow {
	
	module distdebug {
		
		interface Inspectable {
			string evaluate(in string expression);
			string execute(in string code);
		};
		
		interface Pauser {
			boolean locked(in string identifier);
		};
	};
	
};
